/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class CalculatorGUI extends javax.swing.JFrame {
    String angka;
    double jumlah,bil1,bil2;
    int pilih;
    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
        angka ="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textHasil = new javax.swing.JTextField();
        tombol7 = new javax.swing.JButton();
        tombol4 = new javax.swing.JButton();
        tombol1 = new javax.swing.JButton();
        tombolTitik = new javax.swing.JButton();
        tombol8 = new javax.swing.JButton();
        tombol5 = new javax.swing.JButton();
        tombol2 = new javax.swing.JButton();
        tombol0 = new javax.swing.JButton();
        tombol9 = new javax.swing.JButton();
        tombol6 = new javax.swing.JButton();
        tombol3 = new javax.swing.JButton();
        tombolClear = new javax.swing.JButton();
        tombolTambah = new javax.swing.JButton();
        tombolKurang = new javax.swing.JButton();
        tombolKali = new javax.swing.JButton();
        tombolSamaDengan = new javax.swing.JButton();
        tombolBackspace = new javax.swing.JButton();
        tombolbagi = new javax.swing.JButton();
        tombolPersen = new javax.swing.JButton();
        tombolExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tombol7.setText("7");
        tombol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol7ActionPerformed(evt);
            }
        });

        tombol4.setText("4");
        tombol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol4ActionPerformed(evt);
            }
        });

        tombol1.setText("1");
        tombol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol1ActionPerformed(evt);
            }
        });

        tombolTitik.setText(".");
        tombolTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTitikActionPerformed(evt);
            }
        });

        tombol8.setText("8");
        tombol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol8ActionPerformed(evt);
            }
        });

        tombol5.setText("5");
        tombol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol5ActionPerformed(evt);
            }
        });

        tombol2.setText("2");
        tombol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol2ActionPerformed(evt);
            }
        });

        tombol0.setText("0");
        tombol0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol0ActionPerformed(evt);
            }
        });

        tombol9.setText("9");
        tombol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol9ActionPerformed(evt);
            }
        });

        tombol6.setText("6");
        tombol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol6ActionPerformed(evt);
            }
        });

        tombol3.setText("3");
        tombol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombol3ActionPerformed(evt);
            }
        });

        tombolClear.setText("C");
        tombolClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolClearActionPerformed(evt);
            }
        });

        tombolTambah.setText("+");
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolKurang.setText("-");
        tombolKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKurangActionPerformed(evt);
            }
        });

        tombolKali.setText("*");
        tombolKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKaliActionPerformed(evt);
            }
        });

        tombolSamaDengan.setText("=");
        tombolSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSamaDenganActionPerformed(evt);
            }
        });

        tombolBackspace.setText("B");
        tombolBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBackspaceActionPerformed(evt);
            }
        });

        tombolbagi.setText("/");
        tombolbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbagiActionPerformed(evt);
            }
        });

        tombolPersen.setText("%");
        tombolPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPersenActionPerformed(evt);
            }
        });

        tombolExit.setText("E");
        tombolExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombol7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombol4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolKali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombol1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tombolPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombolTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombol0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tombolBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tombolExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombol7)
                    .addComponent(tombol8)
                    .addComponent(tombol9)
                    .addComponent(tombolTambah)
                    .addComponent(tombolKurang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolbagi)
                    .addComponent(tombolKali)
                    .addComponent(tombol6)
                    .addComponent(tombol5)
                    .addComponent(tombol4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolPersen)
                    .addComponent(tombolSamaDengan)
                    .addComponent(tombol3)
                    .addComponent(tombol2)
                    .addComponent(tombol1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolExit)
                    .addComponent(tombolBackspace)
                    .addComponent(tombolClear)
                    .addComponent(tombol0)
                    .addComponent(tombolTitik))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSamaDenganActionPerformed
        switch(pilih){
            case 1:
                bil2 = Double.parseDouble(angka);
                jumlah=bil1 + bil2;
                angka = Double.toString(jumlah);
                textHasil.setText(angka);
                break;
            case 2:
                bil2 = Double.parseDouble(angka);
                jumlah=bil1 - bil2;
                angka = Double.toString(jumlah);
                textHasil.setText(angka);
                break;
            case 3:
                bil2 = Double.parseDouble(angka);
                jumlah=bil1 * bil2;
                angka = Double.toString(jumlah);
                textHasil.setText(angka);
                break;
            case 4:
                bil2 = Double.parseDouble(angka);
                jumlah=bil1 / bil2;
                angka = Double.toString(jumlah);
                textHasil.setText(angka);
                break;
            case 5:
                
                jumlah=bil1 / 100;
                angka = Double.toString(jumlah);
                textHasil.setText(angka);
                break;
            default:
                break;
                
            
        }
    }//GEN-LAST:event_tombolSamaDenganActionPerformed

    private void tombolBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBackspaceActionPerformed
        String text = textHasil.getText();
                if (text.length() > 0) {
                    text = text.substring(0, text.length() - 1);
                    textHasil.setText(text);
                }
    }//GEN-LAST:event_tombolBackspaceActionPerformed

    private void tombol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol7ActionPerformed
angka += "7";
textHasil.setText(textHasil.getText()+"7");
    }//GEN-LAST:event_tombol7ActionPerformed

    private void tombol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol8ActionPerformed
angka += "8";
textHasil.setText(textHasil.getText()+"8");

    }//GEN-LAST:event_tombol8ActionPerformed

    private void tombol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol9ActionPerformed
angka += "9";
textHasil.setText(textHasil.getText()+"9");

    }//GEN-LAST:event_tombol9ActionPerformed

    private void tombol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol4ActionPerformed
angka += "4";
textHasil.setText(textHasil.getText()+"4");

    }//GEN-LAST:event_tombol4ActionPerformed

    private void tombol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol5ActionPerformed
angka += "5";
textHasil.setText(textHasil.getText()+"5");

    }//GEN-LAST:event_tombol5ActionPerformed

    private void tombol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol6ActionPerformed
angka += "6";
textHasil.setText(textHasil.getText()+"6");

    }//GEN-LAST:event_tombol6ActionPerformed

    private void tombol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol1ActionPerformed
angka += "1";
textHasil.setText(textHasil.getText()+"1");

    }//GEN-LAST:event_tombol1ActionPerformed

    private void tombol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol2ActionPerformed
angka += "2";
textHasil.setText(textHasil.getText()+"2"); 

    }//GEN-LAST:event_tombol2ActionPerformed

    private void tombol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol3ActionPerformed
angka += "3";
textHasil.setText(textHasil.getText()+"3");

    }//GEN-LAST:event_tombol3ActionPerformed

    private void tombol0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol0ActionPerformed
        angka += "0";
        textHasil.setText(textHasil.getText()+"0");
    }//GEN-LAST:event_tombol0ActionPerformed

    private void tombolTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTitikActionPerformed
angka += ",";
textHasil.setText(textHasil.getText()+"."); 
    }//GEN-LAST:event_tombolTitikActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        bil1 = Double.parseDouble(angka);
        textHasil.setText("+");
        angka ="";
        pilih=1;
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombolClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolClearActionPerformed
        textHasil.setText("");
        bil1 =0;
        bil2 =0;
        jumlah =0;
        angka ="";
    }//GEN-LAST:event_tombolClearActionPerformed

    private void tombolKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKurangActionPerformed
        bil1 = Double.parseDouble(angka);
        textHasil.setText("-");
        angka ="";
        pilih=2;
    }//GEN-LAST:event_tombolKurangActionPerformed

    private void tombolKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKaliActionPerformed
        bil1 = Double.parseDouble(angka);
        textHasil.setText("*");
        angka ="";
        pilih=3;
    }//GEN-LAST:event_tombolKaliActionPerformed

    private void tombolbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbagiActionPerformed
        bil1 = Double.parseDouble(angka);
        textHasil.setText("/");
        angka ="";
        pilih=4;
    }//GEN-LAST:event_tombolbagiActionPerformed

    private void tombolPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPersenActionPerformed
        bil1 = Double.parseDouble(angka);
        textHasil.setText("%");
        angka ="";
        pilih=5;
    }//GEN-LAST:event_tombolPersenActionPerformed

    private void tombolExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolExitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"apa anda yakin untuk keluar ?","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_tombolExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textHasil;
    private javax.swing.JButton tombol0;
    private javax.swing.JButton tombol1;
    private javax.swing.JButton tombol2;
    private javax.swing.JButton tombol3;
    private javax.swing.JButton tombol4;
    private javax.swing.JButton tombol5;
    private javax.swing.JButton tombol6;
    private javax.swing.JButton tombol7;
    private javax.swing.JButton tombol8;
    private javax.swing.JButton tombol9;
    private javax.swing.JButton tombolBackspace;
    private javax.swing.JButton tombolClear;
    private javax.swing.JButton tombolExit;
    private javax.swing.JButton tombolKali;
    private javax.swing.JButton tombolKurang;
    private javax.swing.JButton tombolPersen;
    private javax.swing.JButton tombolSamaDengan;
    private javax.swing.JButton tombolTambah;
    private javax.swing.JButton tombolTitik;
    private javax.swing.JButton tombolbagi;
    // End of variables declaration//GEN-END:variables
}
